import {
    Expression1,
    Expression2,
    Expression3,
    Expression4,
    Expression5,
    Expression6,
    Expression7,
    ExpressionIsolatedIcon1,
    ExpressionIsolatedIcon2,
    ExpressionIsolatedIcon3,
    ExpressionIsolatedIcon4,
    ExpressionIsolatedIcon5,
    ExpressionIsolatedIcon6,
    ExpressionIsolatedIcon7,
    FacialStyle1,
    FacialStyle2,
    FacialStyle3,
    FacialStyle4,
    FacialStyle5,
    FacialStyle6,
    FacialStyleIsolatedIcon1,
    FacialStyleIsolatedIcon2,
    FacialStyleIsolatedIcon3,
    FacialStyleIsolatedIcon4,
    FacialStyleIsolatedIcon5,
    HairColor1,
    HairColor2,
    HairColor3,
    HairColor4,
    HairStyle1,
    HairStyle1Color1IsolatedIcon,
    HairStyle1Color2IsolatedIcon,
    HairStyle1Color3IsolatedIcon,
    HairStyle1Color4IsolatedIcon,
    HairStyle2,
    HairStyle2Color1IsolatedIcon,
    HairStyle2Color2IsolatedIcon,
    HairStyle2Color3IsolatedIcon,
    HairStyle2Color4IsolatedIcon,
    HairStyle3,
    HairStyle3Color1IsolatedIcon,
    HairStyle3Color2IsolatedIcon,
    HairStyle3Color3IsolatedIcon,
    HairStyle3Color4IsolatedIcon,
    Hat1,
    Hat2,
    Hat3,
    Hat4,
    Hat5,
    Hat6,
    Hat7,
    Hat8,
    Hat9,
    HatIsolatedIcon1,
    HatIsolatedIcon2,
    HatIsolatedIcon3,
    HatIsolatedIcon4,
    HatIsolatedIcon5,
    HatIsolatedIcon6,
    HatIsolatedIcon7,
    HatIsolatedIcon8,
    Other1,
    Other2,
    Other3,
    Other4,
    Other5,
    Other6,
    Other7,
    OtherIsolatedIcon1,
    OtherIsolatedIcon2,
    OtherIsolatedIcon3,
    OtherIsolatedIcon4,
    OtherIsolatedIcon5,
    OtherIsolatedIcon6,
} from "./imgImport"

const DressupData = {
    tabs: [
        {
            index: 0,
            title: "hair",
        },
        {
            index: 1,
            title: "face",
        },
        {
            index: 2,
            title: "accessories",
        },
    ],
    hairStyles: [
        {
            index: 0,
            icon: HairStyle1,
            price: "owned",
            unit: "",
            isolatedIcon: {
                "light-gray": HairStyle1Color1IsolatedIcon,
                black: HairStyle1Color2IsolatedIcon,
                white: HairStyle1Color3IsolatedIcon,
                "dark-gray": HairStyle1Color4IsolatedIcon,
            },
            iconTop: "-10px",
            iconLeft: "-4px",
        },
        {
            index: 1,
            icon: HairStyle2,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: {
                "light-gray": HairStyle2Color1IsolatedIcon,
                black: HairStyle2Color2IsolatedIcon,
                white: HairStyle2Color3IsolatedIcon,
                "dark-gray": HairStyle2Color4IsolatedIcon,
            },
            iconTop: "-5px",
            iconLeft: "16px",
        },
        {
            index: 2,
            icon: HairStyle3,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: {
                "light-gray": HairStyle3Color1IsolatedIcon,
                black: HairStyle3Color2IsolatedIcon,
                white: HairStyle3Color3IsolatedIcon,
                "dark-gray": HairStyle3Color4IsolatedIcon,
            },
            iconTop: "-5px",
            iconLeft: "16px",
        },
    ],
    hairColors: [
        {
            index: 0,
            icon: HairColor1,
            price: "owned",
            unit: "",
            color: "light-gray",
        },
        {
            index: 1,
            icon: HairColor2,
            price: "owned",
            unit: "",
            color: "black",
        },
        {
            index: 2,
            icon: HairColor3,
            price: "owned",
            unit: "",
            color: "white",
        },
        {
            index: 3,
            icon: HairColor4,
            price: "100",
            unit: "t",
            color: "dark-gray",
        },
    ],
    facialStyles: [
        {
            index: 0,
            icon: FacialStyle1,
            price: "owned",
            unit: "",
            iconTop: "0px",
            iconLeft: "0px",
        },
        {
            index: 1,
            icon: FacialStyle2,
            price: "owned",
            unit: "",
            isolatedIcon: FacialStyleIsolatedIcon1,
            iconTop: "55px",
            iconLeft: "18px",
        },
        {
            index: 2,
            icon: FacialStyle3,
            price: "owned",
            unit: "",
            isolatedIcon: FacialStyleIsolatedIcon2,
            iconTop: "55px",
            iconLeft: "21px",
        },
        {
            index: 3,
            icon: FacialStyle4,
            price: "owned",
            unit: "",
            isolatedIcon: FacialStyleIsolatedIcon3,
            iconTop: "10px",
            iconLeft: "22px",
        },
        {
            index: 4,
            icon: FacialStyle5,
            price: "owned",
            unit: "",
            isolatedIcon: FacialStyleIsolatedIcon4,
            iconTop: "58px",
            iconLeft: "32px",
        },
        {
            index: 5,
            icon: FacialStyle6,
            price: "owned",
            unit: "",
            isolatedIcon: FacialStyleIsolatedIcon5,
            iconTop: "70px",
            iconLeft: "36px",
        },
    ],
    expressions: [
        {
            index: 0,
            icon: Expression1,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon1,
            iconTop: "23px",
            iconLeft: "24px",
        },
        {
            index: 1,
            icon: Expression2,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon2,
            iconTop: "23px",
            iconLeft: "24px",
        },
        {
            index: 2,
            icon: Expression3,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon3,
            iconTop: "23px",
            iconLeft: "24px",
        },
        {
            index: 3,
            icon: Expression4,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon4,
            iconTop: "23px",
            iconLeft: "24px",
        },
        {
            index: 4,
            icon: Expression5,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon5,
            iconTop: "23px",
            iconLeft: "24px",
        },
        {
            index: 5,
            icon: Expression6,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon6,
            iconTop: "23px",
            iconLeft: "24px",
        },
        {
            index: 6,
            icon: Expression7,
            price: "owned",
            unit: "",
            isolatedIcon: ExpressionIsolatedIcon7,
            iconTop: "23px",
            iconLeft: "24px",
        },
    ],
    hats: [
        {
            index: 0,
            icon: Hat1,
            price: "owned",
            unit: "",
            iconTop: "0px",
            iconLeft: "0px",
        },
        {
            index: 1,
            icon: Hat2,
            price: "owned",
            unit: "",
            isolatedIcon: HatIsolatedIcon1,
            iconTop: "-43px",
            iconLeft: "24px",
        },
        {
            index: 2,
            icon: Hat3,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon2,
            iconTop: "-49px",
            iconLeft: "8.5px",
        },
        {
            index: 3,
            icon: Hat4,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon3,
            iconTop: "-47px",
            iconLeft: "30px",
        },
        {
            index: 4,
            icon: Hat5,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon4,
            iconTop: "-57px",
            iconLeft: "-2px",
        },
        {
            index: 5,
            icon: Hat6,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon5,
            iconTop: "-15px",
            iconLeft: "28px",
        },
        {
            index: 6,
            icon: Hat7,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon6,
            iconTop: "-35px",
            iconLeft: "26px",
        },
        {
            index: 7,
            icon: Hat8,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon7,
            iconTop: "-50px",
            iconLeft: "-10px",
        },
        {
            index: 8,
            icon: Hat9,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: HatIsolatedIcon8,
            iconTop: "-35px",
            iconLeft: "2px",
        },
    ],
    others: [
        {
            index: 0,
            icon: Other1,
            price: "owned",
            unit: "",
        },
        {
            index: 1,
            icon: Other2,
            price: "owned",
            unit: "",
            isolatedIcon: OtherIsolatedIcon1,
            iconTop: "52px",
            iconLeft: "7px",
        },
        {
            index: 2,
            icon: Other3,
            price: "owned",
            unit: "",
            isolatedIcon: OtherIsolatedIcon2,
            iconTop: "27px",
            iconLeft: "15px",
        },
        {
            index: 3,
            icon: Other4,
            price: "0.01",
            unit: "ndb",
            isolatedIcon: OtherIsolatedIcon3,
            iconTop: "27px",
            iconLeft: "15px",
        },
        {
            index: 4,
            icon: Other5,
            price: "unavailable",
            unit: "",
            isolatedIcon: OtherIsolatedIcon4,
            iconTop: "70px",
            iconLeft: "28px",
        },
        {
            index: 5,
            icon: Other6,
            price: "unavailable",
            unit: "",
            isolatedIcon: OtherIsolatedIcon5,
            iconTop: "20px",
            iconLeft: "10px",
        },
        {
            index: 6,
            icon: Other7,
            price: "unavailable",
            unit: "",
            isolatedIcon: OtherIsolatedIcon6,
            iconTop: "20px",
            iconLeft: "55px",
        },
    ],
}
export { DressupData }
