export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_AVATAR_COMPONENT = "CREATE_AVATAR_COMPONENT";
export const FETCH_AVATAR_COMPONENTS = "FETCH_AVATAR_COMPONENTS";
export const CREATE_NEW_AVATAR = "CREATE_NEW_AVATAR";
export const BID_PLACE = "BID_PLACE";
export const SET_CURRENCY = "SET_CURRENCY";