export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_AVATAR_COMPONENT = "CREATE_AVATAR_COMPONENT";
export const FETCH_AVATAR_COMPONENTS = "FETCH_AVATAR_COMPONENTS";
export const FETCH_AVATARS = 'FETCH_AVATARS';
export const CREATE_NEW_AVATAR = "CREATE_NEW_AVATAR";
export const BID_PLACE = "BID_PLACE";
export const GET_USER_TIERS = 'GET_USER_TIERS';
export const CREATE_USER_TIER = 'CREATE_USER_TIER';
export const SET_CURRENCY = "SET_CURRENCY";

export const PAGINATION_SET_PAGE = 'PAGINATION_SET_PAGE';
export const PAGINATION_SET_LIMIT = 'PAGINATION_SET_LIMIT';

export const FETCH_DATA = 'FETCH_DATA';